sudo: required

services:
  - docker

before_install:
  - docker build -t mouadlousimi/docker-react -f Dockerfile.dev .

script:
  - docker run mouadlousimi/docker-react yarn run test -- --coverage

deploy:
  provider: heroku
  api_key: 
    secure: $HEROKU_ACCESS_KEY
  app: "whispering-atoll-34766"
  on:
    branch: master
  